services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    network_mode: host
    environment:
      CONFIG_FILE: /app/src/config.ini
    env_file:
      - .env
    volumes:
      - ./src:/app/src/

  opensips:
    container_name: ai-voice-connector-opensips
    image: opensips/opensips:latest
    ports:
      - "5060:5060/udp"
    volumes:
      - ./cfg/:/etc/opensips/
    network_mode: host


