services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      dockerfile: ./Dockerfile
    network_mode: host
    environment:
      CONFIG_FILE: /src/config.ini
    env_file:
      - .env
    volumes:
      - ./src:/app/src/

  opensips:
    container_name: ai-voice-connector-opensips
    image: opensips/opensips:latest
    volumes:
      - ../cfg/:/etc/opensips/
    network_mode: host
